### ISSUE TITLE
Missing basic doc

### ISSUE THREAD

**Issue by fenix011** [gConnNet/gConn#1]
From the tags used... i can get some clue of.
Yet... , imagine i don't know Ruby nor what this project is aiming at ? ;-)
Have you thought about extending  the README a couple of lines in order to give a couple of guidelines to whom would like to contribute to gConn? umh... or is it intentional to keep it as it is now in terms of objectives/milestones and let it flow ? Bah, forget what i've just said, ...
cheers

**Comment by picoloo** [comment]
Sure Jordila, we have and assembly at sunday to talk about that. The
meeting is in Sol square or 'el culo de caballo'.

Ciao

PD: Vamos lento porque llegaremos lejos :)
